sudo: required

env:
    global:
        - TAG_PATTERN="^[0-9]+(\.[0-9]+){2}(-(alpha|beta|rc))?$"
        - DOCKER_IMAGE=eexit/mirror-http-server:${TRAVIS_TAG:=$TRAVIS_BUILD_NUMBER}

services:
    - docker

before_install:
    - docker login --email=$DOCKER_EMAIL --username=$DOCKER_USER --password=$DOCKER_PASSWD

install:
    - docker build -t $DOCKER_IMAGE .

script:
    - docker run $DOCKER_IMAGE npm test

after_success:
    - if [[ "$TRAVIS_TAG" =~ $TAG_PATTERN ]]; then docker push $DOCKER_IMAGE; fi
