sudo: required

env:
    global:
        - TAG_PATTERN="^[0-9]+(\.[0-9]+){2}(-(alpha|beta|rc))?$"
        - DOCKER_IMAGE=eexit/mirror-http-server
        - DOCKER_TAG=${TRAVIS_TAG:=$TRAVIS_BUILD_NUMBER}

services:
    - docker

before_install:
    - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin

install:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

script:
    - docker run $DOCKER_IMAGE:$DOCKER_TAG npm test

after_success:
    - $(pwd)/docker-push
